import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Lorem Ipsum</h1>
      <h2>Lorem Ipsum</h2>
      <h3>Lorem Ipsum</h3>
      <p>Lorem Ipsum</p>
    </div>
  );
};

export default Home;
